### ISSUE TITLE
opens then immediatly closes the session

### ISSUE THREAD

**Issue by ghost** [stunel/tunnel-client#1]

**Comment by umobiajulu** [comment]
please update your client and check again

**Comment by umobiajulu** [comment]
client now shows actual error messages

**Comment by umobiajulu** [comment]
use version 2.0.4 for now until this connection issue is resolved

**Comment by ghost** [comment]
how to downgrade also i just installed it

**Comment by umobiajulu** [comment]
just do ```npm i -g stunel-client``` i just corrected the error

**Comment by ghost** [comment]
nvm figured it out now

**Comment by umobiajulu** [comment]
so you mean the issue has been resolved?
