### ISSUE TITLE
is it using a vpn by any chance?

### ISSUE THREAD

**Issue by ghost** [stunel/tunnel-client#2]
ok so when reviving a mobile game i got the following error

gotcha!
your location is unsupported

which i never got previously so does this use a sort of vpn is so whats the location

**Comment by umobiajulu** [comment]
no it dosnt

**Comment by ghost** [comment]
uhm does the traffic get redirected to stunel or something like that?

**Comment by umobiajulu** [comment]
yeah, request is limited to 10 per second per ip
